---
- name: Provision and configure resources
  hosts: localhost  # Ansible runs locally

  tasks:
    - name: Provision resources using Terraform
      terraform:
        project_path: "{{ role_path }}/terraform"
        state: present

- name: Wait for two minutes
  hosts: localhost  # Ansible runs locally
  gather_facts: false

  tasks:
    - name: Wait for two minutes
      pause:
        minutes: 2

- name: Configure Docker and run containers
  hosts: docker_host_3  # Update with appropriate target hosts
  gather_facts: false
  vars:
    client_image: pkarisa/client:1.0.0
    backend_image: pkarisa/backend:1.0.0
    app_folder: /opt/yolo

  roles:
    - docker-installation
    - docker-run