---
- name: Provision and configure resources
  hosts: localhost  # Ansible runs locally

   tasks:
    - name: Initialize Terraform
      community.general.terraform:
        project_path: "{{ playbook_dir }}/terraform"
        state: present
        force_init: true

    - name: Wait for the server to complete initializing before proceeding
      pause:
        minutes: 3

- name: Reload host file # Ansible reload the host file to get the newly created host
  hosts: localhost
  tasks:
    - name: Reload host file
      meta: refresh_inventory

- name: Configure Docker and run containers
  hosts: docker_host_3  # Update with appropriate target hosts
  gather_facts: false
  vars:
    client_image: pkarisa/client:1.0.0
    backend_image: pkarisa/backend:1.0.0
    app_folder: /opt/yolo

  roles:
    - docker-installation
    - docker-run